[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python -c \"from app.database import init_db; init_db()\""]

[start]
cmd = "python run.py"
